package pojo;
// Generated 10-may-2020 15:48:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer idEquipo;
     private int victorias;
     private int derrotas;
     private String nombre;
     private String escudo;
     private Set jugadoreses = new HashSet(0);

    public Equipos() {
    }

	
    public Equipos(int victorias, int derrotas, String nombre, String escudo) {
        this.victorias = victorias;
        this.derrotas = derrotas;
        this.nombre = nombre;
        this.escudo = escudo;
    }
    public Equipos(int victorias, int derrotas, String nombre, String escudo, Set jugadoreses) {
       this.victorias = victorias;
       this.derrotas = derrotas;
       this.nombre = nombre;
       this.escudo = escudo;
       this.jugadoreses = jugadoreses;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public int getVictorias() {
        return this.victorias;
    }
    
    public void setVictorias(int victorias) {
        this.victorias = victorias;
    }
    public int getDerrotas() {
        return this.derrotas;
    }
    
    public void setDerrotas(int derrotas) {
        this.derrotas = derrotas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEscudo() {
        return this.escudo;
    }
    
    public void setEscudo(String escudo) {
        this.escudo = escudo;
    }
    public Set getJugadoreses() {
        return this.jugadoreses;
    }
    
    public void setJugadoreses(Set jugadoreses) {
        this.jugadoreses = jugadoreses;
    }




}


