package pojo;
// Generated 10-may-2020 15:48:46 by Hibernate Tools 4.3.1



/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private int dni;
     private Equipos equipos;
     private String nombre;
     private String apellido;
     private String posicion;
     private int edad;
     private int dorsal;

    public Jugadores() {
    }

    public Jugadores(int dni, Equipos equipos, String nombre, String apellido, String posicion, int edad, int dorsal) {
       this.dni = dni;
       this.equipos = equipos;
       this.nombre = nombre;
       this.apellido = apellido;
       this.posicion = posicion;
       this.edad = edad;
       this.dorsal = dorsal;
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPosicion() {
        return this.posicion;
    }
    
    public void setPosicion(String posicion) {
        this.posicion = posicion;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public int getDorsal() {
        return this.dorsal;
    }
    
    public void setDorsal(int dorsal) {
        this.dorsal = dorsal;
    }




}


