/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.Transaction;
import pojo.Equipos;

/**
 *
 * @author jesuk
 */
public class AgregarEquipo extends javax.swing.JFrame {

    

    /**
     * Creates new form AgregarEquipo
     */
    public AgregarEquipo() {
        initComponents();
        setTitle("Agregar equipo");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNombreEquipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputVictoriasEquipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputDerrotasEquipo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnExplotarArchivos = new javax.swing.JButton();
        outputResultadoPath = new javax.swing.JLabel();
        btnGuardarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Complete los siguientes campos para agregar un equipo.");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Victorias:");

        inputVictoriasEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputVictoriasEquipoActionPerformed(evt);
            }
        });

        jLabel4.setText("Derrotas:");

        jLabel5.setText("Escudo:");

        btnExplotarArchivos.setText("Explorar Archivos");

        outputResultadoPath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputResultadoPath.setText("Resultado Path");

        btnGuardarEquipo.setText("Guardar equipo");
        btnGuardarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputDerrotasEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(inputVictoriasEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(inputNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 86, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(btnExplotarArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(outputResultadoPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputVictoriasEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputDerrotasEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnExplotarArchivos))
                .addGap(27, 27, 27)
                .addComponent(outputResultadoPath)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarEquipo)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEquipoActionPerformed


        if (validateFields()) {
            
            Session mSession = controlador.Controller.getSessionFactory().openSession();
            Transaction mTransaction = mSession.beginTransaction();
            String nombre = inputNombreEquipo.getText().toString().trim();
            int victorias = Integer.parseInt(inputVictoriasEquipo.getText().toString());
            int derrotas = Integer.parseInt(inputDerrotasEquipo.getText().toString());
            String escudo = outputResultadoPath.getText().toString();
            
            Equipos nuevoEquipo = new Equipos();
            nuevoEquipo.setNombre(nombre);
            nuevoEquipo.setVictorias(victorias);
            nuevoEquipo.setDerrotas(derrotas);
            nuevoEquipo.setEscudo(escudo);
            
            mSession.save(nuevoEquipo);
            mTransaction.commit();
            
            mSession.close();
            mTransaction = null;
            
            JOptionPane.showMessageDialog(rootPane, "El equipo "+nuevoEquipo.getNombre()+" se agregó correctamente","Enhorabuena!",JOptionPane.INFORMATION_MESSAGE);
            inputNombreEquipo.setText("");
            inputDerrotasEquipo.setText("");
            inputVictoriasEquipo.setText("");
            inputNombreEquipo.requestFocus();
        }

    }//GEN-LAST:event_btnGuardarEquipoActionPerformed

    private void inputVictoriasEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputVictoriasEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputVictoriasEquipoActionPerformed

    @Override
    public void setDefaultCloseOperation(int operation) {
        dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExplotarArchivos;
    private javax.swing.JButton btnGuardarEquipo;
    private javax.swing.JTextField inputDerrotasEquipo;
    private javax.swing.JTextField inputNombreEquipo;
    private javax.swing.JTextField inputVictoriasEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel outputResultadoPath;
    // End of variables declaration//GEN-END:variables

    private boolean validateFields() {
        if (inputNombreEquipo.getText().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el nombre", "Atención", JOptionPane.INFORMATION_MESSAGE);
            inputNombreEquipo.requestFocus();
            return false;
        }

        if (inputVictoriasEquipo.getText().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar las victorias", "Atención", JOptionPane.INFORMATION_MESSAGE);
            inputVictoriasEquipo.requestFocus();
            return false;
        }

        if (inputDerrotasEquipo.getText().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar las derrotas", "Atención", JOptionPane.INFORMATION_MESSAGE);
            inputDerrotasEquipo.requestFocus();
            return false;
        }
        return true;
    }
}
